import { ArrowUpRight, Building2, MessageSquareText, WalletCards } from "lucide-react";
import Link from "next/link";
import { DataUnavailable } from "@/components/super-admin/unavailable";
import { platformMetrics } from "@/lib/super-admin/data";
import { getSuperAdminAccess } from "@/lib/super-admin/access";

/**
 * Super admin overview page component that displays platform-wide metrics and quick navigation.
 * @returns The super admin dashboard with metrics, school management, and SMS analytics links
 */
export default async function SuperAdminOverview() {
  const access = await getSuperAdminAccess();
  return <main className="mx-auto max-w-7xl px-6 py-8 sm:px-10 lg:px-12"><header className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-gold">Platform overview</p><h1 className="mt-2 font-serif text-4xl font-semibold text-navy">Good morning, platform admin.</h1><p className="mt-3 text-muted">A clear view of the schools and services running on ScholarDesk.</p></div><div className="rounded-lg border border-line bg-white px-4 py-3 text-xs font-semibold text-muted">{access.status === "unavailable" ? "Setup mode" : "Platform access"}</div></header><div className="mt-8"><DataUnavailable /></div><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{platformMetrics.map((metric, index) => { const Icon = [Building2, WalletCards, Building2, MessageSquareText, WalletCards, WalletCards][index]; return <div key={metric.label} className="rounded-xl border border-line bg-white p-5 shadow-[var(--shadow)]"><div className="flex items-center justify-between"><div className="grid size-10 place-items-center rounded-lg bg-gold-soft text-navy"><Icon size={18} /></div><span className="text-xs font-bold text-muted">Unavailable</span></div><p className="mt-6 text-sm text-muted">{metric.label}</p><p className="mt-1 font-serif text-2xl font-semibold text-navy">{metric.value}</p><p className="mt-2 text-xs text-muted">{metric.detail}</p></div>; })}</section><section className="mt-8 grid gap-5 lg:grid-cols-2"><Link href="/super-admin/schools" className="group rounded-xl bg-navy p-6 text-white"><div className="flex items-center justify-between"><Building2 className="text-gold" size={24} /><ArrowUpRight className="text-white/60 transition group-hover:text-gold" size={19} /></div><h2 className="mt-10 font-serif text-2xl">Manage schools</h2><p className="mt-2 max-w-sm text-sm leading-6 text-white/65">Review school status and configure independent module access.</p></Link><Link href="/super-admin/sms-analytics" className="group rounded-xl border border-line bg-white p-6"><div className="flex items-center justify-between"><MessageSquareText className="text-gold" size={24} /><ArrowUpRight className="text-muted transition group-hover:text-navy" size={19} /></div><h2 className="mt-10 font-serif text-2xl text-navy">SMS analytics</h2><p className="mt-2 max-w-sm text-sm leading-6 text-muted">Monitor delivery, usage, allocation thresholds, and platform cost.</p></Link></section></main>;
}