import { BarChart3, ChevronDown, Filter } from "lucide-react";
import { DataUnavailable } from "@/components/super-admin/unavailable";

const columns = ["School", "Total SMS", "Estimated cost", "Students", "Usage", "Delivery"];

/**
 * SMS analytics page component that displays platform-wide SMS usage and delivery metrics.
 * @returns The SMS analytics page with metrics and usage table
 */
export default function SmsAnalyticsPage() {
  return <main className="mx-auto max-w-7xl px-6 py-8 sm:px-10 lg:px-12"><header className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-gold">Platform intelligence</p><h1 className="mt-2 font-serif text-4xl font-semibold text-navy">SMS analytics</h1><p className="mt-3 text-muted">Monitor usage and delivery across every school.</p></div><button type="button" disabled className="inline-flex cursor-not-allowed items-center gap-2 rounded-lg border border-line bg-white px-4 py-3 text-sm font-bold text-navy opacity-50"><ChevronDown size={17} /> Active term</button></header><div className="mt-8"><DataUnavailable title="SMS analytics is waiting for notification data" /></div><section className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-xl bg-navy p-5 text-white"><BarChart3 className="text-gold" size={20} /><p className="mt-7 text-sm text-white/65">Total SMS this term</p><p className="mt-1 font-serif text-3xl">Unavailable</p></div><div className="rounded-xl border border-line bg-white p-5"><p className="text-sm text-muted">Estimated SMS cost</p><p className="mt-7 font-serif text-3xl text-navy">Unavailable</p></div><div className="rounded-xl border border-line bg-white p-5"><p className="text-sm text-muted">Profit margin</p><p className="mt-7 font-serif text-3xl text-navy">—</p><p className="mt-2 text-xs text-muted">Revenue data not configured.</p></div></section><section className="mt-8 rounded-xl border border-line bg-white shadow-[var(--shadow)]"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-line p-5"><h2 className="font-serif text-2xl font-semibold text-navy">Usage by school</h2><button type="button" disabled className="inline-flex cursor-not-allowed items-center gap-2 rounded-lg border border-line px-3 py-2 text-sm font-semibold text-muted opacity-60"><Filter size={16} /> All alerts</button></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-paper text-xs uppercase tracking-wider text-muted"><tr>{columns.map((column) => <th key={column} className="px-5 py-4 font-bold">{column}</th>)}</tr></thead><tbody><tr><td colSpan={columns.length} className="px-5 py-14 text-center"><p className="font-serif text-xl font-semibold text-navy">No analytics available</p><p className="mt-2 text-sm text-muted">Connect notifications_log, students, terms, and platform settings to calculate this table.</p></td></tr></tbody></table></div></section></main>;
}